ALTER TABLE `user`
MODIFY COLUMN `staff_fulltime`  varchar(255) NULL DEFAULT NULL AFTER `service_area`,
ADD COLUMN `fund_info`  varchar(255) NULL AFTER `is_blocked`,
ADD COLUMN `accountant_status`  varchar(10) NULL AFTER `documented_month`,
ADD COLUMN `has_board`  varchar(5) NULL AFTER `accountant_status`,
ADD COLUMN `info_platform`  varchar(255) NULL AFTER `register_type`,
ADD COLUMN `org_rules`  varchar(255) NULL AFTER `info_platform`,
ADD COLUMN `has_plan`  int NULL AFTER `org_rules`,
ADD COLUMN `plan_file`  varchar(255) NULL AFTER `has_plan`,
ADD COLUMN `has_report`  int NULL AFTER `plan_file`,
ADD COLUMN `report_file`  varchar(255) NULL AFTER `has_report`,
ADD COLUMN `project_scale`  varchar(63) NULL AFTER `report_file`,
ADD COLUMN `member_experience`  varchar(63) NULL AFTER `project_scale`,
ADD COLUMN `media_report`  varchar(63) NULL AFTER `member_experience`,
ADD COLUMN `gov_level`  varchar(63) NULL AFTER `media_report`,
ADD COLUMN `has_reward`  int NULL AFTER `gov_level`,
ADD COLUMN `reward_detail`  text NULL AFTER `has_reward`,
ADD COLUMN `participant_scale`  varchar(63) NULL AFTER `reward_detail`,
ADD COLUMN `key_resource`  text NULL AFTER `financial_link`,
ADD COLUMN `partner_info`  text NULL AFTER `key_resource`;
